In [4]:
import sys
sys.path.insert(0,"../")

from src.optimizers.neioptimizer import *
from src.utils.config import CONFIG
CONFIG

{'distribute': {'computer_list': ['tst008@acet116-lnx-10.bucknell.edu',
   'tst008@acet116-lnx-11.bucknell.edu',
   'tst008@acet116-lnx-12.bucknell.edu',
   'localhost'],
  'max_jobs': 1,
  'min_gpu': 500},
 'optimizer': {'num_restarts': 10,
  'raw_samples': 500,
  'options': {'batch_limit': 5, 'max_iter': 200, 'seed': 0}}}

In [2]:
bounds = {
    'x1': (0,1),
    'x2': (0,1),
    'x3': (0,1),
    'x4': (0,1),
    'x5': (0,1),
    'x6': (0,1)
}
optimizer = NEIOptimizer(bounds, device="cpu")

In [13]:
class ToyFunctionTrainer():
    
    NOISE_SE = 0.5
    NOISE_OF_NOISE = 0.1
    NOISE_FURTHER = 0.2

import torch

dtype = float
train_x = torch.tensor([2,3], dtype=dtype)
exact_objective = train_x[0] ** 2 - (train_x[1] - 1) ** 2 + 1
observed_noise = ToyFunctionTrainer.NOISE_SE * torch.randn_like(exact_objective) + \
                 ToyFunctionTrainer.NOISE_OF_NOISE * torch.randn_like(exact_objective)
noisy_objective = exact_objective + observed_noise + \
                  ToyFunctionTrainer.NOISE_FURTHER * torch.randn_like(exact_objective)
{"result": (
    float(noisy_objective.cpu().numpy()), 
    float(observed_noise.cpu().numpy())
)}

{'result': (0.7298500774779506, 0.14578367815575727)}

In [15]:
import time
start = time.time()
time.sleep(1)
elapsed = time.time() - start
elapsed

1.0012941360473633

In [34]:
import datetime
start = datetime.datetime.now()
time.sleep(1)
datetime.datetime.now() - start

datetime.timedelta(seconds=1, microseconds=970)

In [79]:
datetime.datetime.now().strftime("%m/%d/%Y-%H:%M:%S")

'05/29/2020-21:57:10'

In [65]:
(datetime.datetime(2020, 5, 30, 23) - datetime.datetime.now()).seconds / 3600

1.0927777777777778

In [95]:
import json
print(json.dumps([{1:232, 2:343, "this": {"shiet":0, "is":1}}, {1:434, 2:555}], indent=None))

[{"1": 232, "2": 343, "this": {"shiet": 0, "is": 1}}, {"1": 434, "2": 555}]


In [40]:
ci(y_nei)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [90]:
from os import path
import os

print(os.chdir("/home/tung/summer"))
with open("notebooks/Untitled.ipynb", 'r') as f:
    print(f.readline())

None
{



In [86]:
target = torch.empty(3, dtype=torch.long).random_(5)
target

tensor([4, 2, 2])

In [87]:
torch.randn(3, 5, requires_grad=True)

tensor([[ 1.1401, -0.9596, -0.7716, -0.2779, -0.5351],
        [-1.3308, -0.2641, -1.3861, -0.2534, -1.1528],
        [-0.5103,  1.4937, -1.1248, -2.0627, -1.1546]], requires_grad=True)